### ISSUE TITLE
Add an update procedure

### ISSUE THREAD

**Issue by Bratdaking** [mmk2410/intellij-idea-community#1]
Dear Marcel,

Would it be possible to include a little text document that describes what you do when you update? For the newest version I tried to copy what you did, but I am quite stuck. If I understand what you do, I could add a pull requests to this github for the newest version.

Cheers,
Bart

**Comment by Bratdaking** [comment]
Hey Marcel,

I sort of figured it out, so hereby a pull request for version 15.0.1. It is tested, and works. If I should do something differently, just indicate it. And feel free to discard this request.

Cheers,
Bart

**Comment by mmk2410** [comment]
This is quit a good idea. I never thought of this. I have also the idea of writing a bash script, that does the changes. I will write the instructions into the readme file as soon as I have time to do so.
