### ISSUE TITLE
Community version 2017.1 has "uglier" fonts

### ISSUE THREAD

**Issue by raqua** [mmk2410/intellij-idea-community#3]
Hi, 

I have left similar message on Phabricator (as I am not sure where to contact you, sorry for double post). Since upgrading from 2016.3 (?) to 2017.1 my fonts look somewhat worse. It is hard to describe, but it changed. I have not changed anything in my config, still using Source Code Pro font, but all fonts look worse. If needed, I will provide screenshots to compare (I do not have old install available atm.).
I am on Linux Mint 18.1. 
Please let me know how I can assist with this issue resolution. 
Thank you. 

Martin

**Comment by mmk2410** [comment]
I rather work with my Phabricator instance for issues. See https://phab.mmk2410.org/T213
Sorry for the troubles.
